-- DARSHAN SACRED & MYSTERY CONTENT
-- Run once in Supabase SQL Editor after the existing Daily Motivation SQL.

create table if not exists public.darshan_stories (
    id bigint generated by default as identity primary key,
    publish_date date not null default current_date,
    category text not null check (category in ('temple','mystery','ancient','spiritual','video')),
    title text not null,
    excerpt text not null,
    story text not null,
    image_url text,
    video_url text,
    source_name text,
    source_url text,
    published boolean not null default true,
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now()
);

alter table public.darshan_stories enable row level security;

create policy "Public can read published Darshan stories"
on public.darshan_stories
for select to anon, authenticated
using (published = true);

create policy "Admins can insert Darshan stories"
on public.darshan_stories
for insert to authenticated
with check (exists (select 1 from public.daily_motivation_admins where user_id = auth.uid()));

create policy "Admins can update Darshan stories"
on public.darshan_stories
for update to authenticated
using (exists (select 1 from public.daily_motivation_admins where user_id = auth.uid()))
with check (exists (select 1 from public.daily_motivation_admins where user_id = auth.uid()));

create policy "Admins can delete Darshan stories"
on public.darshan_stories
for delete to authenticated
using (exists (select 1 from public.daily_motivation_admins where user_id = auth.uid()));

create or replace function public.set_darshan_stories_updated_at()
returns trigger language plpgsql as $$
begin new.updated_at = now(); return new; end; $$;

drop trigger if exists darshan_stories_updated_at on public.darshan_stories;
create trigger darshan_stories_updated_at
before update on public.darshan_stories
for each row execute function public.set_darshan_stories_updated_at();
