-- DARSHAN DAILY MOTIVATION
-- Run this entire file once in Supabase > SQL Editor.

create table if not exists public.daily_motivation (
    id bigint generated by default as identity primary key,
    publish_date date not null unique,
    title text not null,
    motivation text not null,
    quote text,
    history text,
    reflection text,
    published boolean not null default true,
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now()
);

alter table public.daily_motivation enable row level security;

-- Public visitors can read published posts only.
drop policy if exists "Public can read published motivation" on public.daily_motivation;
create policy "Public can read published motivation"
on public.daily_motivation
for select
to anon, authenticated
using (published = true);

-- Admin allow-list.
create table if not exists public.daily_motivation_admins (
    user_id uuid primary key references auth.users(id) on delete cascade
);

alter table public.daily_motivation_admins enable row level security;

-- Admins can see the allow-list entry for themselves.
drop policy if exists "Admins can read own admin record" on public.daily_motivation_admins;
create policy "Admins can read own admin record"
on public.daily_motivation_admins
for select
to authenticated
using (user_id = auth.uid());

-- Admins can create posts.
drop policy if exists "Admins can insert motivation" on public.daily_motivation;
create policy "Admins can read all motivation"
on public.daily_motivation
for select
to authenticated
using (
    exists (
        select 1
        from public.daily_motivation_admins
        where user_id = auth.uid()
    )
);

create policy "Admins can insert motivation"
on public.daily_motivation
for insert
to authenticated
with check (
    exists (
        select 1 from public.daily_motivation_admins
        where user_id = auth.uid()
    )
);

-- Admins can update posts.
drop policy if exists "Admins can update motivation" on public.daily_motivation;
create policy "Admins can update motivation"
on public.daily_motivation
for update
to authenticated
using (
    exists (
        select 1 from public.daily_motivation_admins
        where user_id = auth.uid()
    )
)
with check (
    exists (
        select 1 from public.daily_motivation_admins
        where user_id = auth.uid()
    )
);

-- Admins can delete posts.
drop policy if exists "Admins can delete motivation" on public.daily_motivation;
create policy "Admins can delete motivation"
on public.daily_motivation
for delete
to authenticated
using (
    exists (
        select 1 from public.daily_motivation_admins
        where user_id = auth.uid()
    )
);

-- Automatically keep updated_at current.
create or replace function public.set_daily_motivation_updated_at()
returns trigger
language plpgsql
as $$
begin
    new.updated_at = now();
    return new;
end;
$$;

drop trigger if exists daily_motivation_updated_at on public.daily_motivation;
create trigger daily_motivation_updated_at
before update on public.daily_motivation
for each row
execute function public.set_daily_motivation_updated_at();

-- After creating your Supabase Auth user, run:
-- insert into public.daily_motivation_admins (user_id)
-- values ('YOUR-SUPABASE-AUTH-USER-UUID');
